module.exports = {
  "rootDir": "../..",
  "transform": {},
  "testMatch": [
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-account-poi.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-account-store.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-note-provenance.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-poi-membership.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-poi-prove-job.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-poi-shape-data.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-selector.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-source-capture.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-txid-verifier.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-own-witness.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-poi-cold-validation.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-poi-output-recovery.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-poi-prover.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-poi-shield-selector.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-poi-source-capture.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-poi-verifier.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-private-proof.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-public-run.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-relay-proof.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-relay-run.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-relay-transact-provenance.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-relay-transact-staging.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-session-worker.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-session.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-shield-prepare.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-shield-receive.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-source-ledger-prefix.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-source-ledger.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-store.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-transact-provenance.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-transact-staging.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-txid-root.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-txid-runner.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-wallet-coverage-store.test.js",
    "<rootDir>/tools/owner-test-staging/tests/src/main/wallet/railgun-wallet-run.test.js"
  ]
};
